defmodule Rho.Stdlib.Uploads.Handle do
  @moduledoc """
  An uploaded file's metadata. Pure data — no behavior.

  - `id` is `"upl_" <> 16 hex chars` — generated by `Uploads.Server.put/2`.
  - `path` is the stable absolute path on disk under the per-session tmp dir.
  - `observation` is filled in lazily by `Observer.observe/2` on first call
    and cached for subsequent calls within the same session.
  """

  alias Rho.Stdlib.Uploads.Observation

  @type t :: %__MODULE__{
          id: String.t(),
          session_id: String.t(),
          filename: String.t(),
          mime: String.t(),
          size: non_neg_integer(),
          path: String.t(),
          uploaded_at: DateTime.t(),
          observation: Observation.t() | nil
        }

  defstruct [
    :id,
    :session_id,
    :filename,
    :mime,
    :size,
    :path,
    :uploaded_at,
    observation: nil
  ]
end
